server:
  port: 9004
#数据库连接
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 5
    # registerWithEureka是否向注册中心注册自己
    register-with-eureka: true
    # fetchRegistry是否需要去检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    ## 主动失效检测间隔,配置成5秒
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: true
    ## 心跳阈值计算周期，如果开启自我保护模式，可以改一下这个配置
    renewal-threshold-update-interval-ms: 120000
    use-read-only-response-cache: false
spring:
  shardingsphere:
    enabled: true
    datasource:
      names: master0,master1
      master0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/ms0?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
        username: root
        password: root
      master1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/ms1?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
        username: root
        password: root
    #分库分表
    sharding:
      default-data-source-name: master1
      #不分库（seata undolog无法安装分库键正确路由）
      tables:
        order:
          actualDataNodes: master$->{1}.order$->{0..1}
          databaseStrategy:
            inline:
              shardingColumn: user_id
              algorithm-expression: master$->{1}
        tableStrategy:
          inline:
            shardingColumn: loan_id
            algorithm-expression: order$->{loan_id % 2}
            key-generate-strategy:
              column: loan_id
              key-generator-name: snowflake
              worker.id: 123
        user:
          actualDataNodes: master$->{1}.user$->{0..1}
          databaseStrategy:
            inline:
              shardingColumn: age
              algorithm-expression: master$->{1}
          tableStrategy:
            inline:
              shardingColumn: uid
              algorithm-expression: user$->{uid % 2}
              key-generate-strategy:
                column: id
                key-generator-name: snowflake
                worker.id: 123
          #根据spi配置手动订单号生产策略


#          key-generator:
#            column: order_id
#            type: AtomicLong
#            props:
#              worker.id: 123

# Seata 配置项，对应 SeataProperties 类
seata:
  enabled: true
  application-id: demo
  tx-service-group: store_tx_group
  registry:
    type: eureka
    eureka:
      service-url: http://localhost:8761/eureka
  config:
    type: file
  use-jdk-proxy: true


thirdparty:
  rest-template:
    readTimeout: 30 #单位：秒
    connectTimeout: 30
    connectionRequestTimeout: 30
    maxTotal: 1000
    defaultMaxPerRoute: 1000
  remote:
    host: http://127.0.0.1:80
    url_test: http://127.0.0.1:80

#xxl:
#  job:
#    admin:
#      addresses:
#    executor:
#      appname: institution-ucredit
#      ip: 127.0.0.1
#      port: 9999
#      logpath: /tmp





