server:
  port: 9004
spring:
  profiles: dev
  datasource:
    master:
      jdbc-url:
      username: admin
      password: admin
      driverClassName: com.mysql.cj.jdbc.Driver
      validation-query: SELECT 1
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    slave:
      jdbc-url:
      username: admin
      password: admin
      driverClassName: com.mysql.cj.jdbc.Driver
      validation-query: SELECT 1
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
  mail:
    host:
    port:
    username:
    password:
    from:
    cc:
    to:
  rabbitmq:
    host:
    port:
    username:
    password:
    virtual-host:
    exchange:
      direct:
        ucredit: direct.exchange.dev
    queue:
      notify: queue.notify.dev
  redis:
    host:
    port:
    password:
    jedis:
      pool:
#        max-wait: -1
        max-idle: 8
        min-idle: 0
        max-active: 8
#    timeout: 0



thirdparty:
  rest-template:
    readTimeout: 30 #单位：秒
    connectTimeout: 30
    connectionRequestTimeout: 30
    maxTotal: 1000
    defaultMaxPerRoute: 1000
  remote:
    host:
    url_test:

xxl:
  job:
    admin:
      addresses:
    executor:
      appname: institution-ucredit
      ip: 127.0.0.1
      port: 9999
      logpath: /tmp




spring:
  shardingsphere:
      props.sql.show=true
      datasource.names=master0,slave0,master1,slave1
    datasource.master0.type=com.alibaba.druid.pool.DruidDataSource
    datasource.master0.driver-class-name=com.mysql.jdbc.Driver
    datasource.master0.url=jdbc:mysql://localhost:3306/ms0?characterEncoding=utf-8
    datasource.master0.username=root
      datasource.master0.password=root
    :
    :

    datasource.slave0.type=com.alibaba.druid.pool.DruidDataSource
    datasource.slave0.driver-class-name=com.mysql.jdbc.Driver
    datasource.slave0.url=jdbc:mysql://localhost:3306/sl0?characterEncoding=utf-8
    datasource.slave0.username=root
      datasource.slave0.password=root

    datasource.master1.type=com.alibaba.druid.pool.DruidDataSource
    datasource.master1.driver-class-name=com.mysql.jdbc.Driver
    datasource.master1.url=jdbc:mysql://localhost:3306/ms1?characterEncoding=utf-8
    datasource.master1.username=root
      datasource.master1.password=root
    datasource.slave1.type=com.alibaba.druid.pool.DruidDataSource
    datasource.slave1.driver-class-name=com.mysql.jdbc.Driver
    datasource.slave1.url=jdbc:mysql://localhost:3306/sl1?characterEncoding=utf-8
    datasource.slave1.username=root
      datasource.slave1.password=root
    sharding.default-database-strategy.inline.sharding-column=age
      sharding.default-database-strategy.inline.algorithm-expression=master$->{age % 2}
    sharding.tables.tab_user.actual-data-nodes=master$->{0..1}.tab_user$->{0..1}
    sharding.tables.tab_user.table-strategy.inline.sharding-column=id
      sharding.tables.tab_user.table-strategy.inline.algorithm-expression=tab_user$->{id % 2}
    sharding.master-slave-rules.master0.master-data-source-name=master0
    sharding.master-slave-rules.master0.slave-data-source-names=slave0
    sharding.master-slave-rules.master1.master-data-source-name=master1
    sharding.master-slave-rules.master1.slave-data-source-names=slave1
